### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by ludwikbukowski** [newrelic/elixir_agent#17]
**Describe the bug**
When I added `@trace` adnotations in few places in the code and run all tests I experience a lot of errors from `new_relic_agent`

**Environment**
* Elixir & Erlang version (`elixir -v`): 20 and 1.6.5
* Agent version (`mix deps | grep new_relic_agent`):  1.0.2

Samples:
```
17:08:44.865 [error] ** Task <0.6007.0> terminating
** Started from 'Elixir.NewRelic.Harvest.Collector.ErrorTrace.HarvestCycle'
** When function  == #Fun<Elixir.NewRelic.Harvest.Collector.ErrorTrace.Harvester.0.43805112>
**      arguments == []
** Reason for termination ==
** {{killed,{'Elixir.GenServer',call,[<0.1559.0>,send_harvest,5000]}},[{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,836}]},{'Elixir.NewRelic.Harvest.Collector.ErrorTrace.Harvester','-complete/1-fun-0-',1,[{file,"lib/new_relic/harvest/collector/error_trace/harvester.ex"},{line,42}]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,88}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
17:08:44.865 [error] CRASH REPORT Process <0.6007.0> with 0 neighbours exited with reason: {killed,{'Elixir.GenServer',call,[<0.1559.0>,send_harvest,5000]}} in 'Elixir.Task.Supervised':exit/4 line 121
17:08:44.866 [error] ** Task <0.6005.0> terminating
** Started from 'Elixir.NewRelic.Harvest.Collector.TransactionTrace.HarvestCycle'
** When function  == #Fun<Elixir.NewRelic.Harvest.Collector.TransactionTrace.Harvester.0.71467580>
**      arguments == []
** Reason for termination ==
** {{killed,{'Elixir.GenServer',call,[<0.1558.0>,send_harvest,5000]}},[{'Elixir.GenServer',call,3,[{file,"lib/gen_server.ex"},{line,836}]},{'Elixir.NewRelic.Harvest.Collector.TransactionTrace.Harvester','-complete/1-fun-0-',1,[{file,"lib/new_relic/harvest/collector/transaction_trace/harvester.ex"},{line,47}]},{'Elixir.Task.Supervised',do_apply,2,[{file,"lib/task/supervised.ex"},{line,88}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
17:08:44.867 [error] CRASH REPORT Process <0.6005.0> with 0 neighbours exited with reason: {killed,{'Elixir.GenServer',call,[<0.1558.0>,send_harvest,5000]}} in 'Elixir.Task.Supervised':exit/4 line 121
17:08:44.868 [error] ** Task <0.6009.0> terminating
** Started from 'Elixir.NewRelic.Harvest.Collector.TransactionErrorEvent.HarvestCycle'
** When function  == #Fun<Elixir.NewRelic.Harvest.Collector.TransactionErrorEvent.Harvester.0.66859507>
**      arguments == []
** Reason for termination ==
```
```
17:18:18.518 [error] Supervisor 'Elixir.NewRelic.Harvest.Collector.TransactionEvent.HarvesterSupervisor' had child 'Elixir.NewRelic.Harvest.Collector.TransactionEvent.Harvester' started with 'Elixir.NewRelic.Harvest.Collector.TransactionEvent.Harvester':start_link() at <0.1369.0> exit with reason killed in context child_terminated
17:18:21.601 [error] Task #PID<0.5404.0> started from NewRelic.Harvest.Collector.TransactionEvent.HarvestCycle terminating
** (stop) exited in: GenServer.call(#PID<0.1369.0>, :send_harvest, 5000)
    ** (EXIT) killed
    (elixir) lib/gen_server.ex:836: GenServer.call/3
    (new_relic_agent) lib/new_relic/harvest/collector/transaction_event/harvester.ex:46: anonymous fn/1 in NewRelic.Harvest.Collector.TransactionEvent.Harvester.complete/1
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.60780878/0 in NewRelic.Harvest.Collector.TransactionEvent.Harvester.complete/1>
    Args: []
17:18:21.603 [error] Task #PID<0.5402.0> started from NewRelic.Harvest.Collector.CustomEvent.HarvestCycle terminating
** (stop) exited in: GenServer.call(#PID<0.1371.0>, :send_harvest, 5000)
    ** (EXIT) killed
    (elixir) lib/gen_server.ex:836: GenServer.call/3
    (new_relic_agent) lib/new_relic/harvest/collector/custom_event/harvester.ex:54: anonymous fn/1 in NewRelic.Harvest.Collector.CustomEvent.Harvester.complete/1
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.93471100/0 in NewRelic.Harvest.Collector.CustomEvent.Harvester.complete/1>
    Args: []
```
but crashes like this as well:
```
17:09:47.419 [error] GenServer #PID<0.6013.0> terminating
** (UndefinedFunctionError) function :hackney_meck_original.request/5 is undefined (module :hackney_meck_original is not available)
```

**Comment by binaryseed** [comment]
The last error you show might be a clue, the agent uses `HTTPoison` to make requests (via `hackney` erlang lib). If you have some library that mocks out hackney, that might be causing a problem, preventing the harvest cycle from doing it's `send_harvest`.

Additionally, those crash reports are telling me that the HarvestCycle process is getting an exit signal, not that it is crashing itself. I'd need to more about the context in which this happens to tell what is going on.

You could simply disable the agent in the test env using:

```elixir
config :new_relic_agent, harvest_enabled: false
```

Also, we state that the agent requires Elixir 1.7, but you are on 1.6. It runs under 1.6 but we've seen extra verbose logging..

**Comment by ludwikbukowski** [comment]
Indeed it was most likely related with some mocking procedures that were happening during the test.
Thanks
