### ISSUE TITLE
Crash when traced function has a <> in its head

### ISSUE THREAD

**Issue by VitorTrin** [newrelic/elixir_agent#246]
```elixir
  defmodule Traced do
    use NewRelic.Tracer

    defstruct [:key]

    @trace :mod
    def mod(%__MODULE__{key: val <> _}), do: val
  end
```

results in 
```
** (ArgumentError) the left argument of <> operator inside a match should be always a literal binary as its size can't be verified, got: val
```

**Comment by binaryseed** [comment]
Hi, I'd check to see if this is valid even without the trace annotation - I don't think this is legal:

```elixir
iex(1)> val <> _ = "hi"
** (ArgumentError) the left argument of <> operator inside a match should be always a literal binary as its size can't be verified, got: val
    (elixir) lib/kernel.ex:1803: Kernel.invalid_concat_left_argument_error/1
    (elixir) lib/kernel.ex:1775: Kernel.wrap_concatenation/3
    (elixir) lib/kernel.ex:1754: Kernel.extract_concatenations/2
    (elixir) expanding macro: Kernel.<>/2
    iex:1: (file)
```
