### ISSUE TITLE
no function clause matching in NewRelic.DistributedTrace.W3CTraceContext.TraceState.encode_sampled

### ISSUE THREAD

**Issue by rudyyazdi** [newrelic/elixir_agent#281]
**Describe the bug**
Hey, team after upgrading the agent to `1.21.1` we're getting the following error:

```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in NewRelic.DistributedTrace.W3CTraceContext.TraceState.encode_sampled/1
        (new_relic_agent) lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex:212: NewRelic.DistributedTrace.W3CTraceContext.TraceState.encode_sampled(nil)
        (new_relic_agent) lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex:41: NewRelic.DistributedTrace.W3CTraceContext.TraceState.encode/1
        (elixir) lib/enum.ex:1336: Enum.\"-map/2-lists^map/1-0-\"/2
        (elixir) lib/enum.ex:1336: Enum.\"-map/2-lists^map/1-0-\"/2
        (new_relic_agent) lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex:28: NewRelic.DistributedTrace.W3CTraceContext.TraceState.encode/1
        (new_relic_agent) lib/new_relic/distributed_trace/w3c_trace_context.ex:83: NewRelic.DistributedTrace.W3CTraceContext.generate/1
        (new_relic_agent) lib/new_relic/distributed_trace.ex:47: NewRelic.DistributedTrace.distributed_trace_headers/1
        (gateway) lib/web/legacy_adapter/proxy_adapter.ex:34: Gateway.Web.LegacyAdapter.Proxy.instrument_conn/1"
```

I could not reproduce this locally but please let me know if you need more details.

Thanks

**Environment**

Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.1 (compiled with Erlang/OTP 22)

new_relic_agent (Hex package) (mix)
locked at 1.21.1 (new_relic_agent) 84f0dbc8

**Comment by binaryseed** [comment]
Hi there, sorry about this. What version of the agent were you running before upgrading?

**Comment by binaryseed** [comment]
I'm going to push a release that fixes this and keep looking into the cause

**Comment by binaryseed** [comment]
I pushed `1.21.2` which should prevent this error

**Comment by binaryseed** [comment]
One question that might help, did you happen to find an error in the agent log that shows a failure of the agent to connect to New Relic when the app starts?

**Comment by rudyyazdi** [comment]
Hey @binaryseed thanks for your response. I was running `1.17.1`. I'll have a look at the error logs and report back

**Comment by rudyyazdi** [comment]
I did not find any logs for startup but there is another error in there regarding this line `NewRelic.create_distributed_trace_payload(:http)`:

```
%{kind: :error, reason: %FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :encode_sampled, kind: nil, module: NewRelic.DistributedTrace.W3CTraceContext.TraceState}, stack: [{NewRelic.DistributedTrace.W3CTraceContext.TraceState, :encode_sampled, [nil], [file: 'lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex', line: 212]}, {NewRelic.DistributedTrace.W3CTraceContext.TraceState, :encode, 1, [file: 'lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex', line: 41]}, {Enum, :\"-map/2-lists^map/1-0-\", 2, [file: 'lib/enum.ex', line: 1336]}, {Enum, :\"-map/2-lists^map/1-0-\", 2, [file: 'lib/enum.ex', line: 1336]}, {NewRelic.DistributedTrace.W3CTraceContext.TraceState, :encode, 1, [file: 'lib/new_relic/distributed_trace/w3c_trace_context/trace_state.ex', line: 28]}, {NewRelic.DistributedTrace.W3CTraceContext, :generate, 1, [file: 'lib/new_relic/distributed_trace/w3c_trace_context.ex', line: 83]}, {NewRelic.DistributedTrace, :distributed_trace_headers, 1, [file: 'lib/new_relic/distributed_trace.ex', line: 47]}, {Gateway.Web.LegacyAdapter.Proxy, :instrument_conn, 1, [file: 'lib/web/legacy_adapter/proxy_adapter.ex', line: 34]}]}```

**Comment by binaryseed** [comment]
Thanks, could you let me know if the latest agent version has cleared up the error?

**Comment by rudyyazdi** [comment]
Yes, it seems to be fixed. Thanks @binaryseed 🙏
