### ISSUE TITLE
Protocol.UndefinedError in NewRelic.Transaction.Complete.report_transaction_error_event/2

### ISSUE THREAD

**Issue by mrz** [newrelic/elixir_agent#299]
The following crash happens when we shut down our Elixir service: 

```
(Protocol.UndefinedError) protocol Enumerable not implemented for {Task, :await, [%Task{owner: #PID<0.9088.727>, pid: #PID<0.9297.727>, ref: #Reference<0.1972246286.4041736194.58603>}, :infinity]} of type Tuple. This protocol is implemented for the following type(s): Ecto.Adapters.SQL.Stream, DBConnection.PrepareStream, DBConnection.Stream, Timex.Interval, GenEvent.Stream, MapSet, Map, IO.Stream, Range, Function, Date.Range, HashDict, HashSet, File.Stream, Stream, List

(elixir 1.11.2) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir 1.11.2) lib/enum.ex:141: Enumerable.reduce/3
(elixir 1.11.2) lib/enum.ex:3461: Enum.map/2
(new_relic_agent 1.22.2) lib/new_relic/util/error.ex:13: NewRelic.Util.Error.normalize/4
(new_relic_agent 1.22.2) lib/new_relic/transaction/complete.ex:391: NewRelic.Transaction.Complete.report_transaction_error_event/2
(new_relic_agent 1.22.2) lib/new_relic/transaction/complete.ex:23: NewRelic.Transaction.Complete.run/2
(new_relic_agent 1.22.2) lib/new_relic/transaction/reporter.ex:123: NewRelic.Transaction.Reporter.complete_and_purge/1
(elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
(new_relic_agent 1.22.2) anonymous fn() in NewRelic.Transaction.Reporter.complete/2
```

**Environment**
* Elixir & Erlang version (`elixir -v`): `elixir:latest` docker image, at the time of this writing 1.11.3
* Agent version (`mix deps | grep new_relic_agent`): 1.22.2

**Comment by binaryseed** [comment]
Thanks, taking a look
